app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  basic-urls:
    git-hub-basic-url: https://api.github.com
    stack-overflow-basic-url: https://api.stackexchange.com/2.3

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
