app:
  scheduler:
    enable: true
    interval: 20s
    force-check-delay: 40s
  basic-urls:
    git-hub-basic-url: ${GITHUB_BASE_URL:https://api.github.com}
    stack-overflow-basic-url: ${STACKOVERFLOW_BASE_URL:https://api.stackexchange.com/2.3/}
    bot-basic-url: ${BOT_BASE_URL:http://localhost:8090}
  database-access-type: jpa
  retry-clients:
    bot-retry:
      retry-mode: linear
      retry-codes:
        - 400
        - 404
      duration: 500ms
      max-attempts: 3
    git-hub-retry:
      retry-mode: linear
      retry-codes:
        - 400
        - 404
      duration: 500ms
      max-attempts: 3
    stack-overflow-retry:
      retry-mode: linear
      retry-codes:
        - 400
        - 404
      duration: 500ms
      max-attempts: 3
  rate-limits:
    capacity: 10
    tokens: 5
    period: 30s

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:54320/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false

server:
  port: 8080

springdoc.swagger-ui.path: /swagger-ui

logging:
  config: classpath:log4j2-plain.xml
