/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq.tables.records;

import edu.java.scrapper.domain.jooq.tables.Subscribes;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class SubscribesRecord extends TableRecordImpl<SubscribesRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SUBSCRIBES.CHATID</code>.
     */
    public void setChatid(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>SUBSCRIBES.CHATID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>SUBSCRIBES.LINKID</code>.
     */
    public void setLinkid(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>SUBSCRIBES.LINKID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkid() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Subscribes.SUBSCRIBES.CHATID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return Subscribes.SUBSCRIBES.LINKID;
    }

    @Override
    @NotNull
    public Long component1() {
        return getChatid();
    }

    @Override
    @NotNull
    public Long component2() {
        return getLinkid();
    }

    @Override
    @NotNull
    public Long value1() {
        return getChatid();
    }

    @Override
    @NotNull
    public Long value2() {
        return getLinkid();
    }

    @Override
    @NotNull
    public SubscribesRecord value1(@NotNull Long value) {
        setChatid(value);
        return this;
    }

    @Override
    @NotNull
    public SubscribesRecord value2(@NotNull Long value) {
        setLinkid(value);
        return this;
    }

    @Override
    @NotNull
    public SubscribesRecord values(@NotNull Long value1, @NotNull Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubscribesRecord
     */
    public SubscribesRecord() {
        super(Subscribes.SUBSCRIBES);
    }

    /**
     * Create a detached, initialised SubscribesRecord
     */
    @ConstructorProperties({"chatid", "linkid"})
    public SubscribesRecord(@NotNull Long chatid, @NotNull Long linkid) {
        super(Subscribes.SUBSCRIBES);

        setChatid(chatid);
        setLinkid(linkid);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SubscribesRecord
     */
    public SubscribesRecord(edu.java.scrapper.domain.jooq.tables.pojos.Subscribes value) {
        super(Subscribes.SUBSCRIBES);

        if (value != null) {
            setChatid(value.getChatid());
            setLinkid(value.getLinkid());
            resetChangedOnNotNull();
        }
    }
}
