/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Chats implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long telegramid;

    public Chats() {
    }

    public Chats(Chats value) {
        this.telegramid = value.telegramid;
    }

    @ConstructorProperties({"telegramid"})
    public Chats(
        @NotNull Long telegramid
    ) {
        this.telegramid = telegramid;
    }

    /**
     * Getter for <code>CHATS.TELEGRAMID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getTelegramid() {
        return this.telegramid;
    }

    /**
     * Setter for <code>CHATS.TELEGRAMID</code>.
     */
    public void setTelegramid(@NotNull Long telegramid) {
        this.telegramid = telegramid;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Chats other = (Chats) obj;
        if (this.telegramid == null) {
            if (other.telegramid != null) {
                return false;
            }
        } else if (!this.telegramid.equals(other.telegramid)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.telegramid == null) ? 0 : this.telegramid.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Chats (");

        sb.append(telegramid);

        sb.append(")");
        return sb.toString();
    }
}
