/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Subscribes implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long chatid;
    private Long linkid;

    public Subscribes() {}

    public Subscribes(Subscribes value) {
        this.chatid = value.chatid;
        this.linkid = value.linkid;
    }

    @ConstructorProperties({ "chatid", "linkid" })
    public Subscribes(
        @NotNull Long chatid,
        @NotNull Long linkid
    ) {
        this.chatid = chatid;
        this.linkid = linkid;
    }

    /**
     * Getter for <code>SUBSCRIBES.CHATID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatid() {
        return this.chatid;
    }

    /**
     * Setter for <code>SUBSCRIBES.CHATID</code>.
     */
    public void setChatid(@NotNull Long chatid) {
        this.chatid = chatid;
    }

    /**
     * Getter for <code>SUBSCRIBES.LINKID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkid() {
        return this.linkid;
    }

    /**
     * Setter for <code>SUBSCRIBES.LINKID</code>.
     */
    public void setLinkid(@NotNull Long linkid) {
        this.linkid = linkid;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Subscribes other = (Subscribes) obj;
        if (this.chatid == null) {
            if (other.chatid != null)
                return false;
        }
        else if (!this.chatid.equals(other.chatid))
            return false;
        if (this.linkid == null) {
            if (other.linkid != null)
                return false;
        }
        else if (!this.linkid.equals(other.linkid))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.chatid == null) ? 0 : this.chatid.hashCode());
        result = prime * result + ((this.linkid == null) ? 0 : this.linkid.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Subscribes (");

        sb.append(chatid);
        sb.append(", ").append(linkid);

        sb.append(")");
        return sb.toString();
    }
}
