/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.tables;


import edu.java.scrapper.domain.jooq.DefaultSchema;
import edu.java.scrapper.domain.jooq.Keys;
import edu.java.scrapper.domain.jooq.tables.records.SubscribesRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Subscribes extends TableImpl<SubscribesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>SUBSCRIBES</code>
     */
    public static final Subscribes SUBSCRIBES = new Subscribes();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<SubscribesRecord> getRecordType() {
        return SubscribesRecord.class;
    }

    /**
     * The column <code>SUBSCRIBES.CHATID</code>.
     */
    public final TableField<SubscribesRecord, Long> CHATID = createField(DSL.name("CHATID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SUBSCRIBES.LINKID</code>.
     */
    public final TableField<SubscribesRecord, Long> LINKID = createField(DSL.name("LINKID"), SQLDataType.BIGINT.nullable(false), this, "");

    private Subscribes(Name alias, Table<SubscribesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Subscribes(Name alias, Table<SubscribesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>SUBSCRIBES</code> table reference
     */
    public Subscribes(String alias) {
        this(DSL.name(alias), SUBSCRIBES);
    }

    /**
     * Create an aliased <code>SUBSCRIBES</code> table reference
     */
    public Subscribes(Name alias) {
        this(alias, SUBSCRIBES);
    }

    /**
     * Create a <code>SUBSCRIBES</code> table reference
     */
    public Subscribes() {
        this(DSL.name("SUBSCRIBES"), null);
    }

    public <O extends Record> Subscribes(Table<O> child, ForeignKey<O, SubscribesRecord> key) {
        super(child, key, SUBSCRIBES);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public List<ForeignKey<SubscribesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SUBSCRIBES_CHATID_FKEY, Keys.SUBSCRIBES_LINKID_FKEY);
    }

    private transient Chats _chats;
    private transient Links _links;

    /**
     * Get the implicit join path to the <code>PUBLIC.CHATS</code> table.
     */
    public Chats chats() {
        if (_chats == null)
            _chats = new Chats(this, Keys.SUBSCRIBES_CHATID_FKEY);

        return _chats;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINKS</code> table.
     */
    public Links links() {
        if (_links == null)
            _links = new Links(this, Keys.SUBSCRIBES_LINKID_FKEY);

        return _links;
    }

    @Override
    @NotNull
    public Subscribes as(String alias) {
        return new Subscribes(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Subscribes as(Name alias) {
        return new Subscribes(alias, this);
    }

    @Override
    @NotNull
    public Subscribes as(Table<?> alias) {
        return new Subscribes(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Subscribes rename(String name) {
        return new Subscribes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Subscribes rename(Name name) {
        return new Subscribes(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Subscribes rename(Table<?> name) {
        return new Subscribes(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
