/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq;


import edu.java.scrapper.domain.jooq.tables.Chats;
import edu.java.scrapper.domain.jooq.tables.Links;
import edu.java.scrapper.domain.jooq.tables.Subscribes;
import edu.java.scrapper.domain.jooq.tables.records.ChatsRecord;
import edu.java.scrapper.domain.jooq.tables.records.LinksRecord;
import edu.java.scrapper.domain.jooq.tables.records.SubscribesRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatsRecord> CHATS_PKEY = Internal.createUniqueKey(Chats.CHATS, DSL.name("CHATS_PKEY"), new TableField[] { Chats.CHATS.TELEGRAMID }, true);
    public static final UniqueKey<ChatsRecord> CONSTRAINT_3 = Internal.createUniqueKey(Chats.CHATS, DSL.name("CONSTRAINT_3"), new TableField[] { Chats.CHATS.TELEGRAMID }, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_4 = Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_4"), new TableField[] { Links.LINKS.URL }, true);
    public static final UniqueKey<LinksRecord> LINKS_PKEY = Internal.createUniqueKey(Links.LINKS, DSL.name("LINKS_PKEY"), new TableField[] { Links.LINKS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<SubscribesRecord, ChatsRecord> SUBSCRIBES_CHATID_FKEY = Internal.createForeignKey(Subscribes.SUBSCRIBES, DSL.name("SUBSCRIBES_CHATID_FKEY"), new TableField[] { Subscribes.SUBSCRIBES.CHATID }, Keys.CHATS_PKEY, new TableField[] { Chats.CHATS.TELEGRAMID }, true);
    public static final ForeignKey<SubscribesRecord, LinksRecord> SUBSCRIBES_LINKID_FKEY = Internal.createForeignKey(Subscribes.SUBSCRIBES, DSL.name("SUBSCRIBES_LINKID_FKEY"), new TableField[] { Subscribes.SUBSCRIBES.LINKID }, Keys.LINKS_PKEY, new TableField[] { Links.LINKS.ID }, true);
}
